# Generated by Django 2.2.12 on 2022-07-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('score', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('start_date', models.DateField(auto_now=True)),
                ('end_date', models.DateField()),
                ('importance', models.CharField(choices=[('A', 'Urgent and important'), ('B', 'Not urgent and important'), ('C', 'Urgent and not important'), ('D', 'Not urgent and not important')], default='D', max_length=2)),
            ],
        ),
    ]
